### ISSUE TITLE
提一些建议，关于隐私和推送

### ISSUE THREAD

**Issue by SuInk** [wolfbolin/csu-covid19-sign#2]
## 腾讯云函数
腾讯云函数已经支持完整的node.js运行环境，函数可以运行在用户的腾讯云函数上，从而保证不会泄露账号和密码

## [Sever酱](http://sc.ftqq.com/3.version)等免费推送服务
推送服务支持将打卡日志推送到微信。

**Comment by wolfbolin** [comment]
## 云函数
云函数是一个好的建议，能解决高并发等一系列问题
但是我不选择有以下原因：
* 我不想改写现有的开发流
* 我的服务不是node（云函数支持Python我知道）
* 虽有免费额度但是超量使用后会产生费用（服务器已经花了钱为何还要再花钱）
* 自己开发解决一些问题，积累开发经验会比频繁使用云组件更有价值（安全性其实也没有明显差距）

## Server酱
该服务的使用具有一定门槛，向用户解释该服务会产生较高说明成本（外加开发成本）
如果原本已经有自己可以部署的Docker脚本都不使用，为何还期望他们使用server酱
现在已经在服务中附加了短信业务推送通知的功能，对于期望获得提醒的用户也提供了选择

如果你有精力能完成进一步的开发，可以改写并提交commit，我会review你的代码并发布上线

**Comment by SuInk** [comment]
🙄第一次写这种完整的小项目，比我想象中花的时间要长，大致写好了，不过可能有小bug，因为一天只能打卡一次，来不及多试几次了。
还有一件事就是统一认证的tokenId找不到合适的方法拿到，node好像没有可用的库，也有可能是我还没找到正确使用方法
我说的安全性是指开发者不能看到使用者的账号密码哦～
https://github.com/SuInk/csu-auto-sign

**Comment by SuInk** [comment]
> ## 云函数
> 云函数是一个好的建议，能解决高并发等一系列问题
> 但是我不选择有以下原因：
> 
> * 我不想改写现有的开发流
> * 我的服务不是node（云函数支持Python我知道）
> * 虽有免费额度但是超量使用后会产生费用（服务器已经花了钱为何还要再花钱）
> * 自己开发解决一些问题，积累开发经验会比频繁使用云组件更有价值（安全性其实也没有明显差距）
> 
> ## Server酱
> 该服务的使用具有一定门槛，向用户解释该服务会产生较高说明成本（外加开发成本）
> 如果原本已经有自己可以部署的Docker脚本都不使用，为何还期望他们使用server酱
> 现在已经在服务中附加了短信业务推送通知的功能，对于期望获得提醒的用户也提供了选择
> 
> 如果你有精力能完成进一步的开发，可以改写并提交commit，我会review你的代码并发布上线

🙄第一次写这种完整的小项目，比我想象中花的时间要长，大致写好了，不过可能有小bug，因为一天只能打卡一次，来不及多试几次了。
还有一件事就是统一认证的tokenId找不到合适的方法拿到，node好像没有可用的库，也有可能是我还没找到正确使用方法
我说的安全性是指开发者不能看到使用者的账号密码哦～
https://github.com/SuInk/csu-auto-sign

**Comment by wolfbolin** [comment]
项目内容我看到了，从实现角度来讲是没有问题的，tokenId的问题其实也可以通过正则来解决
但是来谈谈为什么没有这么做

1. 使用门槛
首先来看另一个项目：https://github.com/wolfbolin/Tools-for-CSU/tree/master/src/nCOV-sign-in
这个是我在学校要求打卡的第三天就写好的脚本，可以自动通过读取本地配置文件完成登录和签到
但是这个项目除了在计算机学院有学生知道，其他同学完全不知道，也没有寻求使用
该项目内容仅仅需要在配置文件中改账号密码，然后用写好的脚本自动运行Docker即可
那么为什么用户量相比于现在的网站服务如此的少，还是因为有门槛
程序员的目标是需要平衡用户进入的门槛与服务质量的
虽然SCF固然有优势，但是有很高门槛，你的理由没有错，但是还是存在设计缺陷
对不懂代码的用户来说，能用就是最大的收益，信任问题可以凭借口头相传的信用度完善，收益大于风险，所以才会选择
不期望所有目标群体都能接受这个风险，但是也不希望在可接受的群体上强加门槛。

2. 安全性
作为一个以代为打卡为目的服务，空谈安全性是没有意义的，就像要求网络环境是绝对安全的一样。
在本项目的设计过程中，已经最大限度的保护了用户的账户安全，在运行过程中仅在登录流程中使用了密码而未存储
并且在日志的输出与异常处理中，对用户的密码做了处理，防止直接向日志中吐出敏感信息。
所以代码实现上已经做到了“开发者不能看到使用者的账号密码”，看到密码的是代码，但是代码没有输出，因此开发者看不到。
在安全性处理上，这已经达到了大多数代理应用的自觉，如图大多数破解软件一样“信则用，不信自己来”
但是仍然可以被质疑存在阴阳代码，和内存监控等安全技术问题，个人认为这是集中式服务无法避免的。
谁也不能保证数据库是绝对安全的，服务器是绝对私有的，程序员是绝对没有二心的
因此还是那个基本问题，安全和方便，不是二选一的二极管，而是两者平衡的天平

3. 持续维护
在安全性方面，没有什么服务能比在用户手机上安装一个由用户自己写的程序那么安全了，但是这明显是不现实的
要求用户看懂代码已经很困难了，运行环境，代码迭代，持续运行等对计算机专业的很多学生都还是问题
这些问题都是阻止大多数服务形式大规模存在的原因，大多数人只是想要一个合适的懒人包，不懒就不会想用这个服务
对于线上的服务，可以通过一套代码来维护大多数用户的需求，已经是比较快速的代码复用的方案，而且有持续的维护跟进
相较于无人维护，迭代缓慢，无人解答问题的项目而言，LTS版本对于用户又多了一份使他们安心的理由。

**Comment by wolfbolin** [comment]
另外，你的项目中存在cookies更新后无法及时保存的问题，建议使用账号密码直接登录获取cookies，或者连接轻量级的数据库做cookies的缓存与更新。登录的方法、cookies更新的方法，tokenID获取的正则都可以在我的项目中找到。

**Comment by SuInk** [comment]
@wolfbolin 我明白，甚至有些人连邮箱都不会填。当时我只看到了您github的动态，不知道网站已经存在了。
你那个项目我看过，我尝试过了，获取不到tokenId的，统一认证系统的重定向比较难搞，node的库不会自动处理，也有可能我方法不对。不过学校应该快换认证系统了，根据招标网的信息。

**Comment by wolfbolin** [comment]
axios和cheerio我也使用过，个人感觉用js完成类似爬虫的任务还是有些不顺手，尤其在处理各种网络请求过程中缺少支持。
很多cheerio解决不了的问题都转为正则解决了，重定向的话应该有拒绝304的相关语法吧（没探究过，不确定）

**Comment by SuInk** [comment]
@wolfbolin 成功了。。https://www.v2ex.com/t/480582
感谢大佬，感谢v2ex，感谢google，感谢简书，感谢思否；
另外，垃圾csdn，垃圾百度
附上解决思路
![2020-10-02 17-08-33屏幕截图](https://user-images.githubusercontent.com/36656552/97082802-f2124880-163e-11eb-8b3a-e0384a260e0a.png)

**Comment by SuInk** [comment]
@wolfbolin 重新回复一次
感谢大佬，感谢v2ex
https://www.v2ex.com/t/480582
附上解决思路。。。
![2020-10-24 21-16-16屏幕截图](https://user-images.githubusercontent.com/36656552/97083233-34d52000-1641-11eb-9ed7-df2d7543bb1c.png)
