### ISSUE TITLE
另一种形式？（GitHub action）

### ISSUE THREAD

**Issue by GENEVE0086** [wolfbolin/csu-covid19-sign#3]
用过一个项目[bilibili task](https://github.com/srcrs/BilibiliTask),使用的是GitHub action的方法，具体的形式是用户将项目fork到自己的仓库，在secrets中填写参数，然后启动action即可每天定期完成签到工作，我觉得是可以迁移到本项目的，同时可以将服务器的负担转移给GitHub,而且用户也相对不用担心个人数据泄露的问题

**Comment by wolfbolin** [comment]
我认为教会搞不清什么是域名的人什么是fork，是非常困难的事情
更多讨论可参考：Issue #2
